### ISSUE TITLE
S3 integration tests sometimes hang when run in GitHub Actions

### ISSUE THREAD

**Issue by markgoddard** [valeriupredoi/PyActiveStorage#111]
After fixing #106, we sometimes see hanging of the S3 integration tests when run in actions.

While debugging, I added the pytest-timeout extension to get a backtrace during the failure. It happens when using h5py to load the netcdf metadata in the Active object's constructor. Here is an example: https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066

Every time I've seen it there is only a single test failure, but it can happen in any integration test that uses S3.

I have never seen this failure mode when running locally, including when running pytest 100 times in a loop.

**Comment by markgoddard** [comment]
Here is the backtrace:

```
pytest --numprocesses 1
  shell: /usr/bin/bash -l {0}
  env:
    INPUT_RUN_POST: true
    CONDA: /usr/share/miniconda[3](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:3)3
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/runner/work/PyActiveStorage/PyActiveStorage
configfile: setup.cfg
plugins: metadata-3.0.0, html-3.2.0, timeout-2.1.0, cov-[4](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:4).1.0, xdist-3.3.1
timeout: 60.0s
timeout method: signal
timeout func_only: False
created: 1/1 worker
1 worker [49 items]

Exception ignored in: <function File.close at 0x7f10[5](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:5)d895790>
Traceback (most recent call last):
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/h5netcdf/core.py", line 1198, in close
    if not self._closed:
AttributeError: 'File' object has no attribute '_closed'
.....x.Fx.ssssss.................................                        [100%]
=================================== FAILURES ===================================
_______________________ TestActive.testActiveComponents ________________________
[gw0] linux -- Python 3.9.1[6](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:6) /usr/share/miniconda33/envs/activestorage-minio/bin/python3.9

self = <test_harness.TestActive testMethod=testActiveComponents>

    def testActiveComponents(self):
        """
        Shows what we expect an active example test to achieve and provides "the right answer"
        """
>       active = Active(self.testfile, "data", utils.get_storage_type())

tests/test_harness.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
activestorage/active.py:102: in __init__
    with load_from_s3(uri) as _ds:
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/contextlib.py:119: in __enter__
    return next(self.gen)
activestorage/active.py:41: in load_from_s3
    ds = h5netcdf.File(s3file, 'r', invalid_netcdf=True)
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/h5netcdf/core.py:105[7](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:7): in __init__
    self._h5file = self._h5py.File(
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/h5py/_hl/files.py:567: in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/h5py/_hl/files.py:231: in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
h5py/h5f.pyx:106: in h5py.h5f.open
    ???
h5py/h5fd.pyx:163: in h5py.h5fd.H5FD_fileobj_read
    ???
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/fsspec/spec.py:1[8](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:9)00: in readinto
    data = self.read(out.nbytes)
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.[9](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:10)/site-packages/fsspec/spec.py:1790: in read
    out = self.cache._fetch(self.loc, self.loc + length)
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/fsspec/caching.py:156: in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/s3fs/core.py:2185: in _fetch_range
    return _fetch_range(
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/s3fs/core.py:2348: in _fetch_range
    return sync(fs.loop, _inner_fetch, fs, bucket, key, version_id, start, end, req_kw)
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/fsspec/asyn.py:94: in sync
    if event.wait(1):
/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py:581: in wait
    signaled = self._cond.wait(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Condition(<unlocked _thread.lock object at 0x7f[10](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:11)5662a240>, 0)>
timeout = 1

    def wait(self, timeout=None):
        """Wait until notified or until a timeout occurs.
    
        If the calling thread has not acquired the lock when this method is
        called, a RuntimeError is raised.
    
        This method releases the underlying lock, and then blocks until it is
        awakened by a notify() or notify_all() call for the same condition
        variable in another thread, or until the optional timeout occurs. Once
        awakened or timed out, it re-acquires the lock and returns.
    
        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).
    
        When the underlying lock is an RLock, it is not released using its
        release() method, since this may not actually unlock the lock when it
        was acquired multiple times recursively. Instead, an internal interface
        of the RLock class is used, which really unlocks it even when it has
        been recursively acquired several times. Another internal interface is
        then used to restore the recursion level when the lock is reacquired.
    
        """
        if not self._is_owned():
            raise RuntimeError("cannot wait on un-acquired lock")
        waiter = _allocate_lock()
        waiter.acquire()
        self._waiters.append(waiter)
        saved_state = self._release_save()
        gotit = False
        try:    # restore state no matter what (e.g., KeyboardInterrupt)
            if timeout is None:
                waiter.acquire()
                gotit = True
            else:
                if timeout > 0:
>                   gotit = waiter.acquire(True, timeout)
E                   Failed: Timeout >60.0s

/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py:316: Failed
----------------------------- Captured stdout call -----------------------------
Test file is /tmp/tmprzpuuw25/test_bizarre.nc

Created file "/tmp/tmprzpuuw25/test_bizarre.nc" with a variable called "data" with shape (10, 10, 10) and chunking, compression [3, 3, 1],None

----------------------------- Captured stderr call -----------------------------

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~~ Stack of asyncio_0 (139708164380224) ~~~~~~~~~~~~~~~~~~~~~
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)

~~~~~~~~~~~~~~~~~~~~~ Stack of fsspecIO (139708256523840) ~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/fsspec/asyn.py", line 61, in _runner
    result[0] = await coro
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/s3fs/core.py", line 2352, in _inner_fetch
    resp = await fs._call_s3(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/s3fs/core.py", line [11](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:12)3, in _error_wrapper
    return await func(*args, **kwargs)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/client.py", line 354, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/client.py", line 379, in _make_request
    return await self._endpoint.make_request(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 97, in _send_request
    success_response, exception = await self._get_response(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/endpoint.py", line [13](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:14)9, in _get_response
    success_response, exception = await self._do_get_response(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 181, in _do_get_response
    http_response = await self._send(request)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 285, in _send
    return await self.http_session.send(request)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 208, in send
    response = await self._session.request(
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiohttp/client.py", line 558, in _request
    resp = await req.send(conn)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 672, in send
    self._writer = self.loop.create_task(self.write_bytes(writer, conn))
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/asyncio/base_events.py", line 438, in create_task
    task = tasks.Task(coro, loop=self, name=name)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (139708648752704) ~~~~~~~~~~~~~~~~~~~~~
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/execnet/gateway_base.py", line 967, in _thread_receiver
    msg = Message.from_io(io)
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/execnet/gateway_base.py", line 432, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/execnet/gateway_base.py", line 400, in read
    data = self._read(numbytes - len(buf))

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
=============================== warnings summary ===============================
tests/test_bigger_data.py: 7 warnings
tests/unit/test_active.py: 7 warnings
  /usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/zarr/meta.py:290: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return float(v)

tests/test_bigger_data.py: 5 warnings
tests/unit/test_active.py: 5 warnings
  /usr/share/miniconda33/envs/activestorage-minio/lib/python3.9/site-packages/zarr/meta.py:292: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    return int(v)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated html file: file:///home/runner/work/PyActiveStorage/PyActiveStorage/test-reports/report.html -

---------- coverage: platform linux, python 3.9.[16](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:17)-final-0 -----------
Coverage HTML written to dir test-reports/coverage_html
Coverage XML written to file test-reports/coverage.xml

=========================== short test summary info ============================
FAILED tests/test_harness.py::TestActive::testActiveComponents - Failed: Timeout >60.0s
== 1 failed, 40 passed, 6 skipped, 2 xfailed, [24](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:25) warnings in 63.[58](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5336006941/jobs/9670061066#step:12:59)s (0:01:03) ==
Error: Process completed with exit code 1.
```

**Comment by markgoddard** [comment]
Some things I've tried that haven't worked:

* Randomising S3 object names to avoid using the same name between multiple tests
* Running pytest serially (`pytest -n 1`) - this appeared to be working for a while but I had two failures with it yesterday :(

I don't really have time to dig further into this, but my changes are on https://github.com/valeriupredoi/PyActiveStorage/tree/001b017e99a1effdd9e43f753d38e1c81ec690c9

**Comment by valeriupredoi** [comment]
@markgoddard cheers for opening this! A few clarifications and requests from my side, please:

- when reporting a test failure, especially a transitory one, on a remote machine (and not locally, as in this case) it'd be very good to already have a stable code base that I can use to make adjustments, and retrigger - which is the branch you created, but also it'd be good to see what changes have been made, so for that a Draft Pull Request (with DNM or Do Not Merge etc in the title) would be very useful
- looking at the test fails I see that you are trying to run the regular integration tests with the now famous @bnlawrence  `_doit()` - but, those tests should not invoke an open via `s3fs` via `h5netcdf` but rather, a simple open via `netcd4python`; this means that USE_S3 flag is still incorrectly set somewhere/somehow
- we are now planning the backdoor optionality to have S3 files transferred to and loaded directly by the client in case the active storage server is too bust, etc etc - your test fails replicate a little bit such a thing but not quite - there is some s3fs/h5netcdf loading, accidental it seems, and not done correctly

I will open a draft PR off your `is-it-using-s3` branch so I can visualize the code changes and trigger the S3 tests and take it from there :+1:

**Comment by valeriupredoi** [comment]
> These test failures are not related to the S3 active storage server - it's when reading the object directly from S3.

We don't have that implementation yet - please don't jump the gun on that, since we need a correct formalism and used cases implemented for that. That is the case where the client pulls the data from S3 when the activestorage server is busy/unavailable etc - this is, in fact, the next task for me to implement as @bnlawrence @davidhassell and myself have discussed earlier today. Having said that, there shouldn't be issues with that, but I need a proper sitdown with the code and implementation first, then I'll write/adapt tests for this very case :beer:

**Comment by markgoddard** [comment]
To be clear, it's this bit of code (added by you) that uses s3fs/h5netcdf to read the metadata to extract filters, missing data settings, etc.: https://github.com/valeriupredoi/PyActiveStorage/blob/8209cdc4b903dec792855b38b8c8ed8c3dbaec99/activestorage/active.py#L20

**Comment by valeriupredoi** [comment]
indeed - and that works fine for the tests that we set up to test the S3 active storage, I have not yet used that to open an S3 file when the S3 active storage is not available - am planning on getting there within the week after next week, it's very possible I will end up seeing exactly the same intermittent test fails you are seeing on that branch, but please let me get there myself and let me understand what's going on based on a structured implementation, not via overloading some tests that are not supposed to run that way anyway :grin:  :+1:

**Comment by markgoddard** [comment]
One option I considered that would allow us to enable these tests is to stop using s3fs to read the dataset's metadata in load_from_s3, but to download the file and read it from disk.

Of course this isn't a "good" solution because it requires downloading the whole file, but it would work and allow us to enable these tests. There are also questions over the use of h5netcdf, so we're probably not too attached to that solution anyway.

**Comment by valeriupredoi** [comment]
hey @markgoddard here's why the tests fail - have a look at this https://github.com/valeriupredoi/PyActiveStorage/actions/runs/5465837697/jobs/9949877201?pr=113 - a regular POSIX netCDF4 file is instead loaded with s3fs/h5py as a result of passing storage_type="s3" and the hardwiring in active.py at line 102 - phew, was dreading a nasty issue, proves out to be pretty benign :grin:  That loading mechanism needs be used only for S3-hosted files, and not for the POSIX/local files :+1:

**Comment by markgoddard** [comment]
@valeriupredoi the Minio/S3 workflow runs all of the standard integration tests but with USE_S3=True. This results in uploading the test data to S3 and passing storage_type='s3' to Active.

**Comment by markgoddard** [comment]
When test Minio/S3 workflow fails, only one of the test cases actually fails - the others are using S3 and S3 active storage as expected.

**Comment by valeriupredoi** [comment]
ah right you are! Just saw that now myself - we shouldn't probably do that in the case of the test_harness test - that runs the setup in the old unittest style and I am suspecting there are some file I/O race conditions going on there while one test is writing the file while another is trying to open the same file. Have you noticed any fails from others tests, that use uniquely-named files (ie not self.testfile)?

**Comment by markgoddard** [comment]
I did wonder if it was reuse of test file names that was the problem. With parallel tests it probably will cause a problem at some point, whether using local files or S3. However, I tried both randomising the file/object names and running tests sequentially, and neither fixed this issue.

**Comment by valeriupredoi** [comment]
am just gonna xfail all tests in test_harness for USE_S3=True and then we can have a looksee at the other tests see if any fail - my hunch is not; plus, that test_harness really needs an overhaul anyway :+1:

**Comment by markgoddard** [comment]
I saw failures outside of that file, it seemed random.

**Comment by valeriupredoi** [comment]
OK let's see - we'll get to the bottom of it, and even if not, we have to move away from h5netcdf anyway and use an S3-compatible netcdf4python (if we get fails there, then we're in trouble)

**Comment by markgoddard** [comment]
I had a go at downloading the object to the local FS: https://github.com/valeriupredoi/PyActiveStorage/commit/6ca8eea5b0bb0d68c647974aa86155e4036e4e9a

It works locally, but then it always has done... I'll give it a few runs in GA to see if it's reliable.
